# Historical prices data

In [1]:
import pickle
with open('nifty_next_tickers.pickle', 'rb') as f:
    tickers = pickle.load(f)

In [2]:
yahoo_tickers = []
for ticker in tickers:
    ticker = f"{ticker}.NS"
    yahoo_tickers.append(ticker)

In [3]:
start = '2011-03-01'
end = '2020-02-01'

In [4]:
# pass yahoo_tickers in this func by appending '.NS' at the end of tickers' name
import os
import pandas_datareader as web
def get_data_from_yahoo(tickers, start, end):
    if not os.path.exists('prices'):
        os.makedirs('prices')

    for ticker in tickers:
        if not os.path.exists(f"prices/{ticker.split('.')[0]}.csv"):
            df = web.DataReader(ticker, 'yahoo', start, end)
            df.to_csv(f"prices/{ticker.split('.')[0]}.csv")
            print(f'Got {ticker}')
        else:
            print(f'Already have {ticker}')

C:\Users\SKA\.conda\envs\investment\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

In [5]:
# pass yahoo ticker in this func as well
# keeping only the adj close as it adjusts for dividends and stock splits
import pandas as pd
import numpy as np

def compile_data(tickers): 
    main_df = pd.DataFrame()

    for count,ticker in enumerate(tickers):
            df = pd.read_csv(f"prices/{ticker.split('.')[0]}.csv")
            df.set_index('Date', inplace= True)
            name =ticker.split('.')[0]
            df.rename(columns = {'Adj Close': name}, inplace = True)
            df.drop(['Open', 'High', 'Low', 'Close', 'Volume'],1, inplace= True)

            if main_df.empty:
                    main_df = df
            else:
                    main_df = main_df.join(df, how = 'outer')

    main_df.replace('', np.nan)
    main_df.to_csv(f'concatenated_prices.csv') 
    
    return main_df

In [6]:
get_data_from_yahoo(yahoo_tickers, start, end)
prices = compile_data(yahoo_tickers)

Got ADANIPORTS.NS
Got ASIANPAINT.NS
Got AXISBANK.NS
Got BAJAJ-AUTO.NS
Got BAJFINANCE.NS
Got BAJAJFINSV.NS
Got BHARTIARTL.NS
Got INFRATEL.NS
Got BPCL.NS
Got BRITANNIA.NS
Got CIPLA.NS
Got COALINDIA.NS
Got DRREDDY.NS
Got EICHERMOT.NS
Got GAIL.NS
Got GRASIM.NS
Got HCLTECH.NS
Got HDFC.NS
Got HDFCBANK.NS
Got HEROMOTOCO.NS
Got HINDALCO.NS
Got HINDUNILVR.NS
Got ICICIBANK.NS
Got INDUSINDBK.NS
Got INFY.NS
Got IOC.NS
Got ITC.NS
Got JSWSTEEL.NS
Got KOTAKBANK.NS
Got LT.NS
Got M&M.NS
Got MARUTI.NS
Got NESTLEIND.NS
Got NTPC.NS
Got ONGC.NS
Got POWERGRID.NS
Got RELIANCE.NS
Got SHREECEM.NS
Got SBIN.NS
Got SUNPHARMA.NS
Got TCS.NS
Got TATAMOTORS.NS
Got TATASTEEL.NS
Got TECHM.NS
Got TITAN.NS
Got ULTRACEMCO.NS
Got UPL.NS
Got VEDL.NS
Got WIPRO.NS
Got ZEEL.NS
Got ACC.NS
Got ADANITRANS.NS
Got AMBUJACEM.NS
Got ASHOKLEY.NS
Got AUROPHARMA.NS
Got DMART.NS
Got BAJAJHLDNG.NS
Got BANDHANBNK.NS
Got BANKBARODA.NS
Got BERGEPAINT.NS
Got BIOCON.NS
Got BOSCHLTD.NS
Got CADILAHC.NS
Got COLPAL.NS
Got CONCOR.NS
Got DABUR.NS
Got DIVISLAB.NS
Got DLF.NS
Got GICRE.NS
Got GODREJCP.NS
Got HAVELLS.NS
Got HDFCAMC.NS
Got HDFCLIFE.NS
Got HINDPETRO.NS
Got HINDZINC.NS
Got ICICIGI.NS
Got ICICIPRULI.NS
Got IBULHSGFIN.NS
Got INDIGO.NS
Got L&TFH.NS
Got LUPIN.NS
Got MARICO.NS
Got MOTHERSUMI.NS
Got NHPC.NS
Got NMDC.NS
Got NIACL.NS
Got OFSS.NS
Got PAGEIND.NS
Got PETRONET.NS
Got PIDILITIND.NS
Got PEL.NS
Got PFC.NS
Got PGHH.NS
Got PNB.NS
Got SBILIFE.NS
Got SRTRANSFIN.NS
Got SIEMENS.NS
Got UBL.NS
Got MCDOWELL-N.NS
Got IDEA.NS

In [9]:
prices

,ADANIPORTS,ASIANPAINT,AXISBANK,BAJAJ-AUTO,BAJFINANCE,BAJAJFINSV,BHARTIARTL,INFRATEL,BPCL,BRITANNIA,...,PEL,PFC,PGHH,PNB,SBILIFE,SRTRANSFIN,SIEMENS,UBL,MCDOWELL-N,IDEA
Date,,,,,,,,,,,,,,,,,,,,,
2011-03-01,132.202530,178.275635,192.371994,NaN,32.884697,428.716064,292.866730,NaN,44.465050,140.358566,...,321.347198,64.799629,1591.478516,112.768143,NaN,691.535461,796.669067,464.863098,NaN,35.047897
2011-03-03,129.015213,178.638092,195.506546,NaN,32.866074,514.488708,286.404358,NaN,43.433949,141.749466,...,325.544098,65.993752,1569.706909,112.226913,NaN,696.867310,802.478333,469.007477,NaN,34.401550
2011-03-04,126.351181,176.547607,198.267944,NaN,33.877571,530.789001,283.627594,NaN,44.134048,140.910858,...,324.355408,67.962769,1565.832397,111.484650,NaN,717.209167,800.416992,463.037567,NaN,35.429787
2011-03-07,125.114288,176.332947,191.565964,NaN,33.345188,499.886200,281.459229,NaN,42.353462,141.442657,...,326.244049,66.794060,1555.915405,109.958862,NaN,701.258301,802.431458,480.749908,NaN,35.165417
2011-03-08,126.256027,175.973969,195.760269,NaN,33.645958,524.919739,290.481110,NaN,42.749119,142.322159,...,326.943298,64.875847,1557.898560,111.917625,NaN,698.883606,803.368469,482.476746,NaN,36.369926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-27,377.082611,1781.193848,740.250000,2950.119629,4154.800293,9552.239258,514.400024,235.965225,443.468506,3139.416504,...,1696.650024,107.052437,11161.900391,61.349998,992.150024,1080.050049,1542.286377,1261.250000,575.700012,5.800000
2020-01-28,368.873352,1771.980835,737.150024,2929.352051,4203.338867,9625.897461,491.250000,231.818634,455.983276,3146.389160,...,1679.500000,107.191048,11112.500000,60.500000,987.849976,1079.849976,1492.464966,1276.599976,655.900024,5.350000
2020-01-29,379.159668,1789.759399,735.250000,2958.972168,4408.866699,9888.700195,490.250000,239.233704,454.181885,3178.978027,...,1702.300049,109.131577,11160.000000,60.950001,1007.799988,1107.250000,1513.661255,1274.050049,634.799988,5.250000
2020-01-30,373.868134,1797.777222,730.900024,3010.316406,4354.291504,9634.244141,489.799988,240.160583,445.269867,3175.516357,...,1578.099976,110.425262,10926.900391,59.950001,998.250000,1043.650024,1495.436401,1256.050049,634.500000,5.200000
2020-01-31,365.362152,1788.464600,729.299988,3043.381592,4355.888184,9436.104492,496.450012,242.258286,433.229156,3165.625977,...,1545.250000,107.791687,10991.799805,60.450001,994.099976,1020.549988,1485.977173,1264.000000,619.000000,5.300000